version: '3.8'

networks:
  mi_red:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.19.0.0/24

services:
  mysql:
    image: mysql:lts
    networks:
      mi_red:
        ipv4_address: 172.19.0.3
    environment:
      MYSQL_ROOT_PASSWORD: sovier
      MYSQL_DATABASE: sistemaodontologico
      MYSQL_USER: secros
      MYSQL_PASSWORD: sovier
      TZ: 'America/Santiago'
    ports:
      - "3306:3306"
    restart: on-failure
    volumes:
      - mysql_data:/var/lib/mysql
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: "0.5"
        reservations:
          memory: 256M
          cpus: "0.25"

  app-dental:
    networks:
      mi_red:
        ipv4_address: 172.19.0.2
    image: secros18/app-dental-api-mysql:latest
    ports:
      - "443:443"
      - "81:80"
    depends_on:
      - mysql
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      DOTNET_USE_POLLING_FILE_WATCHER: "1"
      NUGET_PACKAGES: "/.nuget/fallbackpackages"
      NUGET_FALLBACK_PACKAGES: "/.nuget/fallbackpackages"
      ASPNETCORE_LOGGING__CONSOLE__DISABLECOLORS: "true"
      ASPNETCORE_URLS: "http://+:81;https://+:443"
      DOTNET_RUNNING_IN_CONTAINER: "true"
      DOTNET_VERSION: "8.0.4"
      ASPNET_VERSION: "8.0.4"
      ASPNETCORE_Kestrel__Endpoints__Https__Certificate__Path: /app/certs/fullchain.pem
      ASPNETCORE_Kestrel__Endpoints__Https__Certificate__KeyPath: /app/certs/privkey.pem
      ASPNETCORE_Kestrel__Endpoints__Https__Url: "https://+:443"
      TZ: America/Santiago
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./https:/https:ro
      - /home/ubuntu/certs-api:/app/certs:ro
    restart: on-failure
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: "0.5"
        reservations:
          memory: 256M
          cpus: "0.25"

  web:
    image: secros18/app-dental-web:latest
    ports:
      - "8080:80"
      - "444:443"
    networks:
      mi_red:
        ipv4_address: 172.19.0.5
    environment:
      - NODE_ENV=production
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - /home/ubuntu/certs:/etc/nginx/ssl:ro
    restart: on-failure
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: "0.5"
        reservations:
          memory: 256M
          cpus: "0.25"

volumes:
  mysql_data:
